# -*- coding: utf-8 -*-
"""sales-forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1daVS5McfLkQ23Lj_eaF6iyGShl4_qXNY
"""

!pip install faker plotly -q

import pandas as pd
import numpy as np
import random
from faker import Faker
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

fake = Faker()

stores = ['Store_A', 'Store_B', 'Store_C', 'Store_D']
items = ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Camera']
regions = ['North', 'South', 'East', 'West']

data = []

for i in range(1000):
    date = fake.date_between(start_date='-2y', end_date='today')
    store = random.choice(stores)
    item = random.choice(items)
    region = random.choice(regions)
    sales = random.randint(10, 500)

    data.append([date, store, item, region, sales])

df = pd.DataFrame(
    data,
    columns=['Date', 'Store', 'Item', 'Region', 'Sales']
)

df.head()

df['Date'] = pd.to_datetime(df['Date'])

print(df.isnull().sum())

df = df.drop_duplicates()

df.info()

print("Total Sales:", df['Sales'].sum())
print("Average Sales:", df['Sales'].mean())
print("Max Sales:", df['Sales'].max())
print("Min Sales:", df['Sales'].min())

trend = df.groupby('Date')['Sales'].sum()

plt.figure(figsize=(12,6))
trend.plot(color='blue')
plt.title("Sales Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.grid(True)
plt.show()

df['Month'] = df['Date'].dt.to_period('M').astype(str)

monthly_sales = df.groupby('Month')['Sales'].sum().reset_index()

fig = px.bar(
    monthly_sales,
    x='Month',
    y='Sales',
    color='Month',
    title='Monthly Sales Analysis'
)

fig.show()

store_sales = df.groupby('Store')['Sales'].sum().reset_index()

fig = px.bar(
    store_sales,
    x='Store',
    y='Sales',
    color='Store',
    title='Store Wise Sales'
)

fig.show()

item_sales = df.groupby('Item')['Sales'].sum().reset_index()

fig = px.bar(
    item_sales,
    x='Item',
    y='Sales',
    color='Item',
    title='Product Wise Sales'
)

fig.show()

region_sales = df.groupby('Region')['Sales'].sum().reset_index()

fig = px.pie(
    region_sales,
    values='Sales',
    names='Region',
    title='Sales Distribution By Region'
)

fig.show()

plt.figure(figsize=(10,6))

sns.histplot(
    data=df,
    x='Sales',
    bins=30,
    kde=True
)

plt.title("Sales Distribution")
plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(
    data=df,
    x='Region',
    y='Sales'
)

plt.title("Sales Outlier Detection")
plt.show()

top_products = (
    df.groupby('Item')['Sales']
    .sum()
    .sort_values(ascending=False)
)

print(top_products)

categorical_cols = ['Store', 'Item', 'Region']

encoded = pd.get_dummies(
    df[categorical_cols],
    drop_first=True
)

corr_df = pd.concat(
    [df[['Sales']], encoded],
    axis=1
)

corr = corr_df.corr()

plt.figure(figsize=(12,8))

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

best_store = store_sales.loc[
    store_sales['Sales'].idxmax(),
    'Store'
]

best_product = item_sales.loc[
    item_sales['Sales'].idxmax(),
    'Item'
]

best_region = region_sales.loc[
    region_sales['Sales'].idxmax(),
    'Region'
]

print("Best Performing Store:", best_store)
print("Best Selling Product:", best_product)
print("Highest Revenue Region:", best_region)